#!/usr/bin/env python3
"""
Stage 2: Embed Bugzilla bug reports and index them into a ChromaDB vector store.

Usage:
    bugzilla-index [--input FILE] [--db DIR] [--batch-size N] [--verbose]
    python index_bugs_to_chroma.py [--input FILE] [--db DIR] [--batch-size N] [--verbose]

Configuration is read from .env (see .env.example).
Resumption is handled by querying ChromaDB for already-indexed IDs — no pickle file.

## Document strategy
Each bug is split into overlapping chunks so that long comment threads (which would
exceed MiniLM's 512-token input limit) are fully retrievable, not silently truncated.

Chunk layout for a bug with N substantive comments (after noise filtering):
  chunk 0  : header + description comment (comment 0) — always present
  chunk k  : header + comments [k*STRIDE .. k*STRIDE + WINDOW], k >= 1
  resolution: header + last substantive comment — always present (if > 1 comment)

All chunks share the same bug_id metadata for deduplication and display.
ChromaDB document IDs use the pattern "<bug_id>_c<k>" so each chunk is addressable.

## Noise filtering
Removed before embedding:
  - Bot/autogenerated IBS/OBS integration messages
  - "Created attachment NNNNN" notices
  - Comments where >60% of lines are quoted ("> ..." prefixes)
"""

import argparse
import json
import logging
import os
import re

from dotenv import load_dotenv
from langchain_core.documents import Document
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from tqdm import tqdm

load_dotenv()

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration from environment
# ---------------------------------------------------------------------------

DEFAULT_EMBED_MODEL = os.getenv("EMBEDDING_MODEL", "sentence-transformers/all-MiniLM-L6-v2")
DEFAULT_CHROMA_DIR  = os.getenv("CHROMA_DIR", "chroma_db")
DEFAULT_INPUT       = os.getenv("BUGZILLA_JSONL", "data/bug_reports.jsonl")
DEFAULT_BATCH_SIZE  = int(os.getenv("INDEX_BATCH_SIZE", "200"))

# Chunking parameters (tuned to MiniLM's 512-token / ~1800-char effective window)
CHUNK_WINDOW = 5   # comments per chunk
CHUNK_STRIDE = 3   # stride between chunks (overlap = WINDOW - STRIDE = 2 comments)
MIN_CHUNK_CHARS = 50  # discard chunks with less than this much content

# Noise filter patterns (applied to comment text)
_BOT_PATTERNS = [
    "This is an autogenerated message for IBS integration",
    "This is an autogenerated message for OBS integration",
    "autogenerated message for IBS",
    "autogenerated message for OBS",
    "bwiedemann+obsbugzillabot",
    "mentioned in https://build.suse.de",
    "mentioned in https://smelt.suse.de",
]


# ---------------------------------------------------------------------------
# Noise filtering
# ---------------------------------------------------------------------------

def _is_noise(comment: dict) -> bool:
    """Return True if this comment should be excluded from embedding."""
    text = comment.get("text", "").strip()
    if not text:
        return True

    # Bot / autogenerated integration messages
    if any(p in text for p in _BOT_PATTERNS):
        return True

    # Attachment creation notices (carry no semantic content)
    if text.startswith("Created attachment"):
        return True

    # Comments that are almost entirely quoted reply text
    lines = text.splitlines()
    if lines:
        quoted = sum(1 for l in lines if l.strip().startswith(">"))
        if quoted / len(lines) > 0.6:
            return True

    return False


def _clean_comments(bug: dict) -> list[dict]:
    """Return the bug's comments with noise entries removed."""
    return [c for c in bug.get("Comments", []) if not _is_noise(c)]


# ---------------------------------------------------------------------------
# Metadata
# ---------------------------------------------------------------------------

def _base_metadata(bug: dict) -> dict:
    """
    Build the shared ChromaDB metadata dict for a bug.
    Includes all fields that support filtering and display.
    ChromaDB metadata values must be str, int, float, or bool — no lists or None.
    """
    # CVE aliases: store as comma-separated string (field added by updated downloader;
    # falls back gracefully to empty string for legacy records)
    aliases = bug.get("aliases", [])
    alias_str = ", ".join(aliases) if isinstance(aliases, list) else str(aliases or "")

    # keywords: same treatment
    keywords = bug.get("keywords", [])
    keyword_str = ", ".join(keywords) if isinstance(keywords, list) else str(keywords or "")

    # whiteboard often carries CVSS score in structured form
    whiteboard = str(bug.get("whiteboard", "") or "")

    return {
        "bug_id":        str(bug.get("bug_number", "unknown")),
        "title":         str(bug.get("title", ""))[:500],
        "product":       str(bug.get("Product", "Unknown")),
        "component":     str(bug.get("Component", "Unknown")),
        "status":        str(bug.get("Status", "Unknown")),
        "resolution":    str(bug.get("Resolution", "") or ""),
        "reported":      str(bug.get("Reported", "Unknown")),
        "last_changed":  str(bug.get("last_change_time", "") or ""),
        "priority":      str(bug.get("priority", "") or ""),
        "severity":      str(bug.get("severity", "") or ""),
        "aliases":       alias_str,    # CVE IDs etc.
        "keywords":      keyword_str,
        "whiteboard":    whiteboard[:500],
        "url":           str(bug.get("url", "") or "")[:500],
    }


# ---------------------------------------------------------------------------
# Header (shared across all chunks of a bug)
# ---------------------------------------------------------------------------

def _bug_header(bug: dict) -> str:
    """Compact structured header prepended to every chunk."""
    meta = _base_metadata(bug)
    lines = [
        f"Bug #{meta['bug_id']}",
        f"Title: {meta['title']}",
        f"Product: {meta['product']} | Version: {bug.get('version', '')}",
        f"Component: {meta['component']}",
        f"Reported: {meta['reported']}",
        f"Status: {meta['status']}",
    ]
    if meta["resolution"]:
        lines.append(f"Resolution: {meta['resolution']}")
    if meta["aliases"]:
        lines.append(f"CVE/Aliases: {meta['aliases']}")
    if meta["priority"]:
        lines.append(f"Priority: {meta['priority']} | Severity: {meta['severity']}")
    if meta["whiteboard"]:
        lines.append(f"Whiteboard: {meta['whiteboard']}")
    if meta["keywords"]:
        lines.append(f"Keywords: {meta['keywords']}")
    lines.append("")   # blank line before content
    return "\n".join(lines)


def _format_comment(c: dict) -> str:
    return f"{c.get('name', 'unknown')} ({c.get('date', '')[:10]}): {c.get('text', '').strip()}"


# ---------------------------------------------------------------------------
# Chunking
# ---------------------------------------------------------------------------

def bug_to_chunks(bug: dict) -> list[tuple[str, dict, str]]:
    """
    Split a bug into (text, metadata, doc_id) tuples ready for ChromaDB.

    Strategy:
      - Filter noise from comments.
      - Chunk 0: header + first comment (the bug description). Always created.
      - Chunks 1..N: header + sliding window of CHUNK_WINDOW comments, stride CHUNK_STRIDE.
      - Resolution chunk: header + last substantive comment (if different from chunk 0).
        Labeled so the LLM knows it is the final resolution.
    """
    bug_id  = str(bug.get("bug_number", "unknown"))
    header  = _bug_header(bug)
    meta    = _base_metadata(bug)
    comments = _clean_comments(bug)

    chunks: list[tuple[str, dict, str]] = []

    if not comments:
        # No substantive comments — embed just the header
        text = header.strip()
        if len(text) >= MIN_CHUNK_CHARS:
            m = {**meta, "chunk": "header", "chunk_index": 0, "total_chunks": 1}
            chunks.append((text, m, f"{bug_id}_c0"))
        return chunks

    # --- Chunk 0: description (first comment) ---
    desc_text = header + "Description:\n" + _format_comment(comments[0])
    if len(desc_text) >= MIN_CHUNK_CHARS:
        m = {**meta, "chunk": "description", "chunk_index": 0, "total_chunks": 0}
        chunks.append((desc_text, m, f"{bug_id}_c0"))

    # --- Middle chunks: sliding window over all comments ---
    if len(comments) > 1:
        starts = list(range(0, len(comments), CHUNK_STRIDE))
        total = len(starts)
        for chunk_idx, start in enumerate(starts):
            window = comments[start: start + CHUNK_WINDOW]
            body = "\n\n".join(_format_comment(c) for c in window)
            text = header + f"Comments (part {chunk_idx + 1} of {total}):\n" + body
            if len(text) >= MIN_CHUNK_CHARS:
                m = {**meta, "chunk": "comments", "chunk_index": chunk_idx + 1,
                     "total_chunks": 0}
                chunks.append((text, m, f"{bug_id}_c{chunk_idx + 1}"))

    # --- Resolution chunk: last substantive comment ---
    last = comments[-1]
    if last is not comments[0]:  # avoid duplicating when there's only one comment
        res_text = header + "Resolution / final status:\n" + _format_comment(last)
        if len(res_text) >= MIN_CHUNK_CHARS:
            m = {**meta, "chunk": "resolution", "chunk_index": 9999,
                 "total_chunks": 0}
            chunks.append((res_text, m, f"{bug_id}_cR"))

    # Back-fill total_chunks now that we know the count
    n = len(chunks)
    chunks = [(t, {**m, "total_chunks": n}, d) for t, m, d in chunks]

    return chunks


# ---------------------------------------------------------------------------
# JSONL streaming reader
# ---------------------------------------------------------------------------

def stream_bugs(input_file: str):
    """Yield bug dicts one at a time from a JSONL file."""
    with open(input_file, "r", encoding="utf-8") as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError as e:
                logger.warning("Skipping corrupt line %d: %s", lineno, e)


def count_lines(input_file: str) -> int:
    with open(input_file, "r") as f:
        return sum(1 for line in f if line.strip())


# ---------------------------------------------------------------------------
# ChromaDB ID tracking
# ---------------------------------------------------------------------------

def get_indexed_bug_ids(vectorstore: Chroma, chroma_dir: str) -> set[str]:
    """
    Return the set of bug_ids already present in the vector store.
    Each bug may have multiple chunk documents; we track by bug_id (from metadata),
    not by individual document ID.

    Uses direct SQLite access to avoid the SQLite variable-count limit that occurs
    when ChromaDB tries to fetch all ~2M row IDs in a single parameterised query.
    Falls back to paginated ChromaDB get() if SQLite access fails.
    """
    import sqlite3

    db_path = os.path.join(chroma_dir, "chroma.sqlite3")
    bug_ids: set[str] = set()

    if os.path.exists(db_path):
        try:
            con = sqlite3.connect(db_path)
            cur = con.cursor()
            # The embedding_metadata table stores key/value pairs per document.
            cur.execute(
                "SELECT DISTINCT string_value FROM embedding_metadata WHERE key = 'bug_id'"
            )
            for (val,) in cur.fetchall():
                if val:
                    bug_ids.add(val)
            con.close()
            logger.info("ChromaDB already contains chunks for %d unique bugs.", len(bug_ids))
            return bug_ids
        except Exception as e:
            logger.warning("Direct SQLite query failed (%s); falling back to paginated get().", e)

    # Paginated fallback: fetch 10,000 rows at a time using offset
    PAGE = 10_000
    offset = 0
    while True:
        result = vectorstore._collection.get(
            limit=PAGE, offset=offset, include=["metadatas"]
        )
        metas = result.get("metadatas", [])
        if not metas:
            break
        for meta in metas:
            if meta and "bug_id" in meta:
                bug_ids.add(meta["bug_id"])
        if len(metas) < PAGE:
            break
        offset += PAGE

    logger.info("ChromaDB already contains chunks for %d unique bugs.", len(bug_ids))
    return bug_ids


def delete_bug_chunks(vectorstore: Chroma, bug_id: str):
    """Delete all chunk documents for a given bug_id."""
    result = vectorstore.get(
        where={"bug_id": bug_id},
        include=[],
    )
    ids = result.get("ids", [])
    if ids:
        vectorstore.delete(ids=ids)
        logger.debug("Deleted %d chunks for bug #%s.", len(ids), bug_id)


# ---------------------------------------------------------------------------
# Main indexing logic
# ---------------------------------------------------------------------------

def index_bugs(input_file: str, chroma_dir: str, batch_size: int, embed_model: str,
               reindex: bool = False):
    """
    Read bugs from input_file (JSONL) and index any not yet in chroma_dir.
    Each bug is split into multiple overlapping chunks before embedding.
    Already-indexed bugs are skipped; bugs re-downloaded via --since are
    deleted (all their chunks) then re-indexed.
    """
    logger.info("Embedding model : %s", embed_model)
    logger.info("ChromaDB dir    : %s", chroma_dir)
    logger.info("Input file      : %s", input_file)
    logger.info("Chunk window    : %d comments, stride %d", CHUNK_WINDOW, CHUNK_STRIDE)

    os.makedirs(chroma_dir, exist_ok=True)

    embedding    = HuggingFaceEmbeddings(model_name=embed_model)
    vectorstore  = Chroma(persist_directory=chroma_dir, embedding_function=embedding)
    indexed_bugs = get_indexed_bug_ids(vectorstore, chroma_dir)

    total_lines  = count_lines(input_file)
    logger.info("Input file has %d records.", total_lines)

    # Accumulate (Document, doc_id) pairs until batch_size bugs have been processed
    doc_batch:  list[Document] = []
    id_batch:   list[str]      = []
    bugs_in_batch = 0

    indexed_count = 0
    skipped_count = 0
    updated_count = 0
    chunk_count   = 0

    bug_iter = tqdm(stream_bugs(input_file), total=total_lines,
                    desc="Indexing bugs", unit="bug")

    for bug in bug_iter:
        bug_id = str(bug.get("bug_number", "unknown"))

        if bug_id in indexed_bugs:
            if reindex:
                # Re-downloaded via --since: delete all old chunks, then re-index
                delete_bug_chunks(vectorstore, bug_id)
                indexed_bugs.discard(bug_id)
                updated_count += 1
                logger.debug("Will re-index bug #%s", bug_id)
            else:
                # Plain resumption: skip already-indexed bugs
                skipped_count += 1
                bug_iter.set_postfix(
                    bugs=indexed_count, chunks=chunk_count,
                    skipped=skipped_count, updated=updated_count,
                )
                continue

        chunks = bug_to_chunks(bug)
        if not chunks:
            skipped_count += 1
            continue

        for text, meta, doc_id in chunks:
            doc_batch.append(Document(page_content=text, metadata=meta))
            id_batch.append(doc_id)

        bugs_in_batch += 1
        chunk_count   += len(chunks)

        if bugs_in_batch >= batch_size:
            _flush(vectorstore, doc_batch, id_batch, indexed_bugs)
            indexed_count += bugs_in_batch
            doc_batch, id_batch, bugs_in_batch = [], [], 0
            bug_iter.set_postfix(
                bugs=indexed_count, chunks=chunk_count,
                updated=updated_count, skipped=skipped_count,
            )

    if bugs_in_batch:
        _flush(vectorstore, doc_batch, id_batch, indexed_bugs)
        indexed_count += bugs_in_batch

    db_file = os.path.join(chroma_dir, "chroma.sqlite3")
    if os.path.exists(db_file):
        size_mb = os.path.getsize(db_file) / (1024 * 1024)
        logger.info("ChromaDB size: %.1f MB", size_mb)

    logger.info(
        "Done. Bugs indexed: %d | Chunks written: %d | Updated: %d | Skipped: %d",
        indexed_count, chunk_count, updated_count, skipped_count,
    )


def _flush(vectorstore: Chroma, docs: list[Document],
           ids: list[str], indexed_bugs: set[str]):
    """Write a batch of Documents to ChromaDB."""
    if not docs:
        return
    try:
        vectorstore.add_documents(docs, ids=ids)
        for doc in docs:
            indexed_bugs.add(doc.metadata["bug_id"])
        logger.debug("Flushed %d chunks.", len(docs))
    except Exception as e:
        logger.error("Failed to flush batch: %s", e)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Index Bugzilla bug reports from JSONL into a ChromaDB vector store."
    )
    parser.add_argument("--input", default=DEFAULT_INPUT, metavar="FILE",
                        help=f"Input JSONL file (default: {DEFAULT_INPUT})")
    parser.add_argument("--db", default=DEFAULT_CHROMA_DIR, metavar="DIR",
                        help=f"ChromaDB directory (default: {DEFAULT_CHROMA_DIR})")
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE, metavar="N",
                        help=f"Bugs per write batch (default: {DEFAULT_BATCH_SIZE})")
    parser.add_argument("--embed-model", default=DEFAULT_EMBED_MODEL, metavar="MODEL",
                        help=f"HuggingFace model (default: {DEFAULT_EMBED_MODEL})")
    parser.add_argument("--verbose", action="store_true", help="Enable DEBUG logging")
    parser.add_argument("--reindex", action="store_true",
                        help="Delete and re-index already-indexed bugs (use after --since download)")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    if not os.path.exists(args.input):
        logger.error("Input file not found: %s", args.input)
        raise SystemExit(1)

    index_bugs(
        input_file=args.input,
        chroma_dir=args.db,
        batch_size=args.batch_size,
        embed_model=args.embed_model,
        reindex=args.reindex,
    )


if __name__ == "__main__":
    main()
